#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.2 on Sun Nov 28 16:40:38 2021
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class SerialSelect(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SerialSelect.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((317, 127))
        self.SetTitle("frame")
        self.Hide()

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.SerialPort = wx.TextCtrl(self.panel_1, wx.ID_ANY, "/dev/ttyUSB0")
        self.SerialPort.SetMinSize((300, 32))
        self.SerialPort.SetToolTip("Serial Port of the programmer")
        sizer_1.Add(self.SerialPort, 0, wx.EXPAND, 0)

        self.SerialBaudRate = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["Baudrate", "19200", "9600"], style=wx.CB_DROPDOWN)
        sizer_1.Add(self.SerialBaudRate, 0, wx.EXPAND, 0)

        self.SerialConnect = wx.Button(self.panel_1, wx.ID_ANY, "Connect to serial port")
        sizer_1.Add(self.SerialConnect, 0, wx.EXPAND, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()
        # end wxGlade

# end of class SerialSelect

class Main(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Main.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 250))
        self.SetTitle("z80 Programmer")
        self.SetFocus()
        self.Show()
        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizerFileSelect = wx.StaticBoxSizer(wx.StaticBox(self.panel_1, wx.ID_ANY, "File Selection"), wx.HORIZONTAL)
        sizer_1.Add(sizerFileSelect, 1, wx.EXPAND, 0)

        self.FileSelect = wx.Button(self.panel_1, wx.ID_ANY, "Select File")
        sizerFileSelect.Add(self.FileSelect, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        SelectedFile = wx.StaticText(self.panel_1, wx.ID_ANY, "Selected File")
        sizerFileSelect.Add(SelectedFile, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 7)

        ProgrammingControls = wx.StaticBoxSizer(wx.StaticBox(self.panel_1, wx.ID_ANY, "Programming"), wx.HORIZONTAL)
        sizer_1.Add(ProgrammingControls, 1, wx.EXPAND, 0)

        self.Write = wx.Button(self.panel_1, wx.ID_ANY, "Write")
        ProgrammingControls.Add(self.Write, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)

        self.Read = wx.Button(self.panel_1, wx.ID_ANY, "Read")
        ProgrammingControls.Add(self.Read, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)

        sizer_2 = wx.StaticBoxSizer(wx.StaticBox(self.panel_1, wx.ID_ANY, "Serial Port Settings"), wx.HORIZONTAL)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)

        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add(sizer_3, 2, wx.ALIGN_CENTER_VERTICAL, 0)

        CurSerialPort = wx.StaticText(self.panel_1, wx.ID_ANY, "Serial Port")
        sizer_3.Add(CurSerialPort, 0, wx.EXPAND, 0)

        CurSerialBaud = wx.StaticText(self.panel_1, wx.ID_ANY, "Baudrate")
        sizer_3.Add(CurSerialBaud, 0, wx.EXPAND, 0)

        self.SetSerialSettings = wx.Button(self.panel_1, wx.ID_ANY, "Settings")
        sizer_2.Add(self.SetSerialSettings, 1, wx.ALIGN_CENTER_VERTICAL, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.Bind(wx.EVT_BUTTON, self.OnFileSelect, self.FileSelect)
        # end wxGlade

    def OnFileSelect(self, event):  # wxGlade: Main.<event_handler>
        print("Event handler 'OnFileSelect' not implemented!")
        event.Skip()

# end of class Main

class MyApp(wx.App):
    def OnInit(self):
        self.SerialSelect = SerialSelect(None, wx.ID_ANY, "")
        self.SetTopWindow(self.SerialSelect)
        self.SerialSelect.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
